"""table added

Revision ID: 13138dc69056
Revises: 9eafe8dee492
Create Date: 2021-09-26 23:39:04.194624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13138dc69056'
down_revision = '9eafe8dee492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchs')
    # ### end Alembic commands ###
